[device]
;io4, nageki, ontroller, yuangeki, simgeki, nyageki
;choose your device
device_name = io4

[idk]
;only for ontroller
;if test_lever only print  '15', set this to 1
idk = 0

[boundary]
;lever left limit and right limit,these are mine
;if your lever is mouse, values mostly are 1000 or -10
; 216 13
;if the direction of lever is wrong, set N_FLAG to 1

L_MAX = 216
R_MAX = 13
N_FLAG = 0

[frequency]
;reading frequency
;defalut is 25ms
;suggest 25ms
;for simgeki, defalut is 15ms
fre = 0.025


