# Generated by Django 5.2.7 on 2025-10-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonConfig',
            fields=[
                ('button_key', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='按钮键值')),
                ('image_name', models.CharField(max_length=100, verbose_name='图片文件名')),
                ('image_path', models.CharField(default='images/buttons/', max_length=200, verbose_name='图片路径')),
            ],
            options={
                'verbose_name': '按钮配置',
                'verbose_name_plural': '按钮配置',
                'db_table': 'button_config',
            },
        ),
    ]
